### ISSUE TITLE
Is sound played not working

### ISSUE THREAD

**Issue by ShapeNaN** [RedWirePlatinumTwo/RedWiresMinecraftMod#3]
Build failed when using "is sound played same as"

Procedure:
![image](https://github.com/user-attachments/assets/cd829818-d264-4ddc-9153-921f1a4ff1c3)

Log: 
![image](https://github.com/user-attachments/assets/96d42356-9b51-40f1-946b-08cc53b4324c)

Element code:
[element.txt](https://github.com/user-attachments/files/16503185/element.txt)

**Comment by RedWirePlatinumTwo** [comment]
It's supposed to be used for the "Sound played from position" or "Sound played at entity" global triggers

**Comment by RedWirePlatinumTwo** [comment]
Hence the "(any sound played event)"

**Comment by ShapeNaN** [comment]
Oh, ok, sorry for bothering then. Thanks for clarifying!
